Fix workflows testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -51,6 +51,20 @@ jobs:
           shellcheck -s bash -x ./src/easydock
 
       # Shunit2 Testing
-      - name: Run shunit2 testing
+      #- name: Run shunit2 testing
+      #  run: |
+      #    bash ./shunit2/run_test.sh
+
+      # Shunit2 Testing
+      - name: Run unit testing
         run: |
-          bash ./shunit2/run_test.sh
+          cd test-app
+          bash ../src/easydock init
+          if [ -f .env.easydock ]; then
+            echo "Init EasyDock success"
+          else
+            echo "Init EasyDock fail"
+            exit 1
+          fi
+          bash ../src/easydock build
+          bash ../src/easydock up
